# Site settings
title: VISUAL DESIGNER
email: your-email@domain.com
url: https://zhoucarol.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "UI designer - Graphic Artist - User Experience Designer"
meta_author: Carol Zhou

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8418bc
  primary-rgb: "24,288,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Carol Zhou
  location: Location
  social: Around the Web
  credits: Visual UI designer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: qq
    url: http://wpa.qq.com/msgrd?v=3&uin=793450319&site=qq&menu=yes
  - title: weixin
    url: http://wpa.qq.com/msgrd?v=3&uin=793450319&site=qq&menu=yes
# Postal address (add as many lines as necessary)
address:
  - line: Jiangsu Province, Lake Road
  - line: Lihu Road, Jiangnan University, 1800

# Credits content
credits: 'Discover the beauty of the world, depicting the world with a brush.'

# Build settings
markdown: kramdown
permalink: pretty
